/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.7 at Mon Nov 10 15:52:41 2014. */

#include "simple.pb.h"



const pb_field_t arduinoToUdoo_fields[7] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, arduinoToUdoo, us_left, us_left, 0),
    PB_FIELD2(  2, INT32   , REQUIRED, STATIC  , OTHER, arduinoToUdoo, us_center, us_left, 0),
    PB_FIELD2(  3, INT32   , REQUIRED, STATIC  , OTHER, arduinoToUdoo, us_right, us_center, 0),
    PB_FIELD2(  4, INT32   , REQUIRED, STATIC  , OTHER, arduinoToUdoo, ir_left, us_right, 0),
    PB_FIELD2(  5, INT32   , REQUIRED, STATIC  , OTHER, arduinoToUdoo, ir_right_front, ir_left, 0),
    PB_FIELD2(  6, INT32   , REQUIRED, STATIC  , OTHER, arduinoToUdoo, ir_right_back, ir_right_front, 0),
    PB_LAST_FIELD
};


