/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.7 at Mon Nov 10 15:52:41 2014. */

#ifndef _PB_SIMPLE_PB_H_
#define _PB_SIMPLE_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _arduinoToUdoo {
    int32_t us_left;
    int32_t us_center;
    int32_t us_right;
    int32_t ir_left;
    int32_t ir_right_front;
    int32_t ir_right_back;
} arduinoToUdoo;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define arduinoToUdoo_us_left_tag                1
#define arduinoToUdoo_us_center_tag              2
#define arduinoToUdoo_us_right_tag               3
#define arduinoToUdoo_ir_left_tag                4
#define arduinoToUdoo_ir_right_front_tag         5
#define arduinoToUdoo_ir_right_back_tag          6

/* Struct field encoding specification for nanopb */
extern const pb_field_t arduinoToUdoo_fields[7];

/* Maximum encoded size of messages (where known) */
#define arduinoToUdoo_size                       66

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
