/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.7 at Tue May 13 16:26:16 2014. */

#include "simple.pb.h"



const pb_field_t arduinoToUdoo_fields[7] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, arduinoToUdoo, us_left, us_left, 0),
    PB_FIELD2(  2, INT32   , REQUIRED, STATIC  , OTHER, arduinoToUdoo, us_center, us_left, 0),
    PB_FIELD2(  3, INT32   , REQUIRED, STATIC  , OTHER, arduinoToUdoo, us_right, us_center, 0),
    PB_FIELD2(  4, INT32   , REQUIRED, STATIC  , OTHER, arduinoToUdoo, ir_left, us_right, 0),
    PB_FIELD2(  5, INT32   , REQUIRED, STATIC  , OTHER, arduinoToUdoo, ir_right_front, ir_left, 0),
    PB_FIELD2(  6, INT32   , REQUIRED, STATIC  , OTHER, arduinoToUdoo, ir_right_back, ir_right_front, 0),
    PB_LAST_FIELD
};

const pb_field_t udooToArduino_fields[6] = {
    PB_FIELD2(  1, INT32   , OPTIONAL, STATIC  , FIRST, udooToArduino, speed, speed, 0),
    PB_FIELD2(  2, INT32   , OPTIONAL, STATIC  , OTHER, udooToArduino, steering, speed, 0),
    PB_FIELD2(  3, BOOL    , OPTIONAL, STATIC  , OTHER, udooToArduino, leftBlink, steering, 0),
    PB_FIELD2(  4, BOOL    , OPTIONAL, STATIC  , OTHER, udooToArduino, rightBlink, leftBlink, 0),
    PB_FIELD2(  5, BOOL    , OPTIONAL, STATIC  , OTHER, udooToArduino, stopLight, rightBlink, 0),
    PB_LAST_FIELD
};


