all:
	g++ trace3.cpp -lopencv_core -lopencv_imgproc -lopencv_highgui	
run3:
	g++ trace3.cpp -lopencv_core -lopencv_imgproc -lopencv_highgui	
	./a.out
run5: 
	g++ trace5.cpp -lopencv_core -lopencv_imgproc -lopencv_highgui	
	./a.out
