/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.4 at Thu Oct  8 18:21:52 2015. */

#ifndef PB_MESSAGEPROTO_PB_H_INCLUDED
#define PB_MESSAGEPROTO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Control {
    uint32_t steering;
    uint32_t acceleration;
    uint32_t lights;
} Control;

typedef struct _Sensors {
    uint32_t usFront;
    uint32_t usRear;
    uint32_t irFrontRight;
    uint32_t irRearRight;
    uint32_t irBackLeft;
    uint32_t irBackRight;
    uint32_t wheelFrontLeft;
    uint32_t wheelRearRight;
} Sensors;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Sensors_init_default                     {0, 0, 0, 0, 0, 0, 0, 0}
#define Control_init_default                     {0, 0, 0}
#define Sensors_init_zero                        {0, 0, 0, 0, 0, 0, 0, 0}
#define Control_init_zero                        {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Control_steering_tag                     1
#define Control_acceleration_tag                 2
#define Control_lights_tag                       3
#define Sensors_usFront_tag                      1
#define Sensors_usRear_tag                       2
#define Sensors_irFrontRight_tag                 3
#define Sensors_irRearRight_tag                  4
#define Sensors_irBackLeft_tag                   5
#define Sensors_irBackRight_tag                  6
#define Sensors_wheelFrontLeft_tag               7
#define Sensors_wheelRearRight_tag               8

/* Struct field encoding specification for nanopb */
extern const pb_field_t Sensors_fields[9];
extern const pb_field_t Control_fields[4];

/* Maximum encoded size of messages (where known) */
#define Sensors_size                             48
#define Control_size                             18

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGEPROTO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
