/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.4-dev at Thu Sep 24 11:44:39 2015. */

#include "simple.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t sensorData_fields[7] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, sensorData, usf, usf, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, sensorData, usb, usf, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, sensorData, irrf, usb, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, sensorData, irrb, irrf, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, sensorData, irrl, irrb, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, sensorData, irrr, irrl, 0),
    PB_LAST_FIELD
};


